# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20160515_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstatistics',
            name='special_abilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.Ability'),
        ),
    ]
